server:
  port: ${SERVER_PORT}
##Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
  instance:
    prefer-ip-address: true
## Swagger docs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
## AWS Config
aws:
  region: ${AWS_REGION}  # Can be changed per environment (e.g., dev, prod)
  sns:
    topic-arn: ${AWS_SNS_TOPIC_ARN} # ARN stands for Amazon Resource Name in AWS. eg arn:aws:sns:<region>:<account-id>:<topic-name>
  endpoint: #http://localhost:4566
  access-key: #test
  secret-key: #test
## kafka Config
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}  # Or Kafka broker URL
  topic:
    name: ${KAFKA_TOPIC_NAME} # Should have been sns ${AWS_SNS_TOPIC_ARN}
  producer:
    retries: ${KAFKA_PRODUCER_RETRIES}
    batch-size: ${KAFKA_PRODUCER_BATCH_SIZE}
    linger-ms: ${KAFKA_PRODUCER_LINGER_MS}
  consumer:
    group-id: withdrawal-group
    auto-offset-reset: earliest
    enable-auto-commit: false
    # Use StringDeserializer for key (assuming the key is a string)
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # Use JsonDeserializer for value (assuming WithdrawalEvent is the value)
    value-deserializer: org.springframework.kafka.core.GenericMessageListenerContainer$ListenerRunnable

## Spring configs
spring:
  application:
    name: BankAccountWithdrawal  #Application name
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:  # Optionally, enable retry for resilience
    config:
      retry:
        enabled: true  # Retry enabled for resilience
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/BankAccountWithdrawal  #JDBC URL for MySQL database
    username: ${DB_USERNAME}  #Use externalized username (environment variable DB_USERNAME)
    password: ${DB_PASSWORD}  #Yes password since DB does not require one
    driver-class-name: com.mysql.cj.jdbc.Driver  #MySQL driver
    hikari:
      connection-timeout: 30000  # Connection timeout in milliseconds
      maximum-pool-size: 20  # Maximum number of connections in the pool, # Increased pool size for handling concurrent connections
      minimum-idle: 5  # Minimum idle connections in the pool
      idle-timeout: 60000  # Idle timeout in milliseconds, # 1 min idle timeout
      max-lifetime: 1800000  # Max lifetime for a connection in milliseconds, # 30 min max lifetime
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQLDialect for MySQL
    hibernate:
      ddl-auto: validate  # Hibernate DDL auto-update for development (use "validate" or "none" in production)
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
## JWT Configuration
JWT_SECRET: ${JWT_SECRET}  # We can still use Hashicorp vault or AWS secret manager,Azure Key Vault and Kubernetes Secrets
expirationMs: 157784630000  # 6 months
## spring logging
logging:
  level:
    org:
      springframework:
        kafka= DEBUG
    com:
      sanlam:
        bankaccountwithdrawal:
          event=DEBUG:
    org.springframework: WARN  # Reduced log verbosity for production
    org.springframework.jdbc: INFO  # Set logging level for Spring JDBC to INFO for production
    com.zaxxer.hikari: DEBUG
## Resilience4j Configuration
resilience4j:
  retry:
    instances:
      withdrawRetry:
        maxAttempts: 5
        waitDuration: 1s
      databaseRetry:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.sql.SQLException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  circuitbreaker:
    instances:
      withdrawCircuitBreaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 15000ms
        slidingWindowSize: 10
## Actuator (Monitoring)
management:
  server:
    port: ${SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: "metrics,health,info,actuator"  # Limited to critical endpoints
  endpoint:
    health:
      show-details: "when_authorized" # "always"
    shutdown:
      enabled: false  # Disable shutdown endpoint in production
    metrics:
      tags:
        application: "BankAccountWithdrawal"
        export:
          prometheus:
            enabled: true